---
services:
  frontend:
    image: registry.pusilkom.com/bapenda/bapenda-pkb-bbnkb-frontend:develop
    networks:
      - bapenda-pkb-bbnkb-development
    expose:
      - "80"
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 16mb
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - NET_BIND_SERVICE
    restart: always

networks:
  bapenda-pkb-bbnkb-development:
    external: true
